### ISSUE TITLE
Bug with an player readying up

### ISSUE THREAD

**Issue by TheCoolsurdy** [aarontwf/BattleNight-Core#123]
Hello,
Whenever my players join the BattleNight arena, they select their class, and they ready up, which works fine. It says 'Player' is ready! However, when the last person to ready up tries to ready up by punching the iron block, nothing happens. No message is displayed. This is the error message I get through the console. 

> Running BattleNight v1.10.0
> Running CraftBukkit version git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks (MC: 1.7.9) (Implementing API version 1.7.9-R0.1-SNAPSHOT)
#### Error message:

```
21.05 19:37:38 [Server] ERROR Could not pass event PlayerInteractEvent to BattleNight v1.10.0
21.05 19:37:38 [Server] INFO org.bukkit.event.EventException
21.05 19:37:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:216) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerInteractManager.dig(PlayerInteractManager.java:103) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:536) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.PacketPlayInBlockDig.a(SourceFile:53) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.PacketPlayInBlockDig.handle(SourceFile:8) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO Caused by: java.lang.IllegalArgumentException: n must be positive
21.05 19:37:38 [Server] INFO at java.util.Random.nextInt(Unknown Source) ~[?:1.7.0_51]
21.05 19:37:38 [Server] INFO at me.limebyte.battlenight.core.battle.SimpleLobby.startBattle(SimpleLobby.java:187) ~[?:?]
21.05 19:37:38 [Server] INFO at me.limebyte.battlenight.core.util.player.BattlePlayer.setReady(BattlePlayer.java:156) ~[?:?]
21.05 19:37:38 [Server] INFO at me.limebyte.battlenight.core.listeners.InteractListener.onPlayerInteract(InteractListener.java:34) ~[?:?]
21.05 19:37:38 [Server] INFO at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
21.05 19:37:38 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
21.05 19:37:38 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
21.05 19:37:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
21.05 19:37:38 [Server] INFO ... 15 more
```

**Comment by Unholyjulien** [comment]
I have the same issue.  I have a player with me join in BN for a test run but we both choose a class and ready up but then nothing happens at all.  Also you guys used to have teams red and blue and now its gone.  I was wondering where is the TDM or is there just no teams anymore.  But i need this fixed so my players can play.

**Comment by aarontwf** [comment]
@Unholyjulien You can change the type of Battle in the config file from FFA to TDM. See [Configuration](https://github.com/BattleNight/BattleNight-Core/wiki/Configuration).

**Comment by Unholyjulien** [comment]
thanks ill try that

**Comment by Unholyjulien** [comment]
the game will still not start thou, thats the main issue

**Comment by aarontwf** [comment]
Fixed in v1.11.0

**Comment by Unholyjulien** [comment]
I think your totally ignoring me to the fact that when 2 people join and
click a class then click the iron to ready up, NOTHING HAPPENS.  I updated
the battle night today, and set all the waypoints and spawns, which I'm a
little upset that there is no longer a blue lounge or red lounge like back
in the day.  just one lounge.  how the heck am I suppose to know whos on my
team.  The fact is it does not work

unleashthe.beastmc.com  Please join the server and help me config my arena
just the first one I can do the rest if I ever make another arena.  I'll
show you it doesn't work.  You obviously do not believe me.

My skype is Unholyjulien
add me for a conversation how to get this working

**Comment by Unholyjulien** [comment]
By the way this is version 1.9.2 for battle night so the issue remains.  also .bn test <test>  how do I get that to work?  Just please contact me to try to get the ready up to work,  everyone is ready but nothing happens still.

**Comment by aarontwf** [comment]
@Unholyjulien Try with v1.11. You can [download it here](http://dev.bukkit.org/bukkit-plugins/battlenight/files/34-battle-night-v1-11-0/).

**Comment by Unholyjulien** [comment]
that works. I am using that 1.11 and it finally works thanks limebyte
